"""add user_id to formulario

Revision ID: 5d7a72d99ec2
Revises: 606b5cc36c4b
Create Date: 2025-08-05 16:41:27.569366

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d7a72d99ec2"
down_revision: Union[str, Sequence[str], None] = "606b5cc36c4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.add_column("formulario", sa.Column("user_id", sa.Integer(), nullable=True))

    # Popula valores antigos com ID do admin (ou outro usuário padrão)
    op.execute("UPDATE formulario SET user_id = 1 WHERE user_id IS NULL")

    # Define a coluna como NOT NULL
    op.alter_column("formulario", "user_id", nullable=False)
    op.create_foreign_key(None, "formulario", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "formulario", type_="foreignkey")
    op.drop_column("formulario", "user_id")
    op.drop_table("user")
    # ### end Alembic commands ###
