"""first migration

Revision ID: 606b5cc36c4b
Revises: 
Create Date: 2025-08-05 11:27:38.759012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '606b5cc36c4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_formulario', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('orientacao_resposta', sa.String(length=255), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('obrigatoria', sa.Boolean(), nullable=False),
    sa.Column('sub_pergunta', sa.Boolean(), nullable=False),
    sa.Column('tipo_pergunta', sa.Enum('SIM_NAO', 'MULTIPLA_ESCOLHA', 'UNICA_ESCOLHA', 'TEXTO_LIVRE', 'INTEIRO', 'NUMERO_DECIMAL', name='enumtipopergunta'), nullable=False),
    sa.ForeignKeyConstraint(['id_formulario'], ['formulario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opcoes_respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pergunta', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.String(length=255), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('resposta_aberta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_pergunta'], ['pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opcoes_resposta_pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_opcao_resposta', sa.Integer(), nullable=False),
    sa.Column('id_pergunta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_opcao_resposta'], ['opcoes_respostas.id'], ),
    sa.ForeignKeyConstraint(['id_pergunta'], ['pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opcoes_resposta_pergunta')
    op.drop_table('opcoes_respostas')
    op.drop_table('pergunta')
    op.drop_table('formulario')
    # ### end Alembic commands ###
